openapi: 3.0.1
info:
  title: Finx Pending Approval List Service
  description: 'Finx Pending Approval List Service.'
  version: 11.0.0
servers:
  - url: 'https://finx-celta-api-dev.fincuro.in'
paths:
  '/v1/fetchUserList':
    post:
      tags:
        - FinxColleagePortalService
      summary: FinxColleagePortalService
      description: FinxColleagePortalService
      operationId: FinxColleagePortalService
      requestBody:
        $ref: '#/components/requestBodies/RetrieveUserRequest'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveUserResponseResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/v1/fetchUserListBasedOnName':
    post:
      tags:
        - FinxColleagePortalService
      summary: FetchUserListBasedOnName
      description: FetchUserListBasedOnName
      operationId: FetchUserListBasedOnName
      requestBody:
         $ref: '#/components/requestBodies/RetrieveCustomerNameRequest'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveCustomerNameResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'      
components:
  schemas:
    retrieveUserResponseResponse:
      type: object
      properties:
        status:
          type: string
          format: string
          description: "\n"
    retrieveCustomerNameResponse:
      type: object
      properties:
        status:
          type: string
          format: string
           description: "\n"
    paging:
          type: object
          properties:
            pageRowCount:
              type: string
              format: string
               description: "\n"
            pageNumber:
              type: string
              format: string
               description: "\n"
    retrieveCustomerNameRequest:      
      type: object
      properties:
        customerName:
          type: string
          format: string 
        paging:
          $ref: '#/components/schemas/paging'   
    retrieveUserRequest:
      type: object
      properties:
        corporateID:
          type: string
          format: string 
        paging:
          $ref: '#/components/schemas/paging'   
    HTTPError:
      type: object
      properties:
        statusCode:
          type: string
          description: "\n"
          format: string
        status:
          type: string
          description: "\n"
          format: string
        message:
          type: string
          description: "\n"
          format: string
  requestBodies:
    retrieveCustomerNameRequest:
      description: RetrieveCustomerNameRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveCustomerNameRequest'
    retrieveUserRequest:
      description: RetrieveUserRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveUserRequest'
  responses:
    retrieveUserResponseResponse:
      description: RetriveUserResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveUserResponseResponse'
    retrieveCustomerNameResponse:
      description: RetriveCustomerNameResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveCustomerNameResponse'        
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'